name: code_scan
description: A flexible code scanner for QR codes, barcodes and many others. Using Google's ML Kit. Use it as a Widget with a camera or use the methods provided, with a camera controller.
version: 1.0.0
repository: https://github.com/DrafaKiller/CodeScanner-flutter
issue_tracker: https://github.com/DrafaKiller/CodeScanner-flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  google_mlkit_barcode_scanning: ^0.14.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0
